version: '3.8'

services:
  johnny-whisper:
    build: .
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - ./server/uploads:/app/server/uploads
    environment:
      - NODE_ENV=production
